version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    ports:
      - "${VIRTUAL_PORT}:80"
      - "9233:443"
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 15m
      TZ: "America/Argentina/Mendoza"
      ND_LOGLEVEL: info 
      ND_PORT: ${VIRTUAL_PORT}
      ND_BASEURL: ""
      ND_ENABLETRANSCODINGCONFIG: "true"
      ND_TRANSCODINGCACHESIZE: "2100MB"
      ND_ENABLECOVERANIMATION: "false"
      ND_DEFAULTLANGUAGE: "es"
      ND_ENABLEDOWNLOAD: "true"
      ND_COVERJPEGQUALITY: "80"
      ND_DEFAULTTHEME: "Spotify-ish"
      ND_SPOTIFY_ID: ${ND_SPOTIFY_ID}
      ND_SPOTIFY_SECRET: ${ND_SPOTIFY_SECRET}
      ND_LASTFM_APIKEY: ${ND_LASTFM_APIKEY}
      ND_LASTFM_LANGUAGE: "es"
      ND_LASTFM_SECRET: ${ND_LASTFM_SECRET}
      ND_AUTOIMPORTPLAYLISTS: "false"
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      VIRTUAL_PORT: ${VIRTUAL_PORT}
      LETSENCRYPT_HOST: ${LET_ENC_HOST}
      LETSENCRYPT_EMAIL: ${LET_ENC_EMAIL}
    volumes:
      - "./data:/data"
      - /music:/music:ro
    networks:
      - music-app
      - nginx-proxy

networks:
  music-app:
  nginx-proxy:
    external:
      name: nginx-proxy
